### ISSUE TITLE
Softskill matrix

### ISSUE THREAD

**Issue by blzzua** [den-vasyliev/SRE-Competence-Matrix#1]
Привіт. Побачив відео та твою матрицю компетенцій, згадав як пару років тому законспектував іншу матрицю софтскилів. Cам доклад: https://www.youtube.com/watch?v=g3oRegcNXQI , презентація https://sandark7.github.io/404Fest2021/# (нажаль російською)

|                       | jun                                                                                       | middle                                                                                                                                                                              | senior                                                             |
|-----------------------|-------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------|
| особиста ефективність | Сприйняття критики<br>Управління емоціями<br>Адаптовуємость<br>Пошук та аналіз інформації | Управління стресом<br>Спрямованість на результат<br>Планування та цілепокладання<br>Управління власним розвитком<br>Тайм менеджмент<br>Рефлексія<br>Ініціативність<br>Самостійність | Багатозадачність                                                   |
| комунікативні навички | Командна робота<br>Вміння слухати                                                         | Письмове спілкування<br>Переконання та аргументація                                                                                                                                 | Емоційний інтелект                                                 |
| навички мислення      | Логічне мислення<br>Відкритість новому                                                    | Системне мислення<br>Критичне мислення<br>Креативність                                                                                                                              | Проектне мислення<br>Вироблення та прийняття рішень                |
| лідерські навички     |                                                                                           | Зворотній зв'язок<br>Відповідальність за результат                                                                                                                                  | Делегування<br>Планування<br>Клієнтоорієнтованість<br>Наставництво |

**Comment by den-vasyliev** [comment]
Привіт! Круто, пропоную додати цю табличку до софтскілів нижнього окремого блоку. Якщо не проти, у джуна заповнимо описом щодо лідерських навичок, а сеньору розпишемо термін "Багатозадачність". Як дивишься на це?

**Comment by blzzua** [comment]
> Привіт! Круто, пропоную додати цю табличку до софтскілів нижнього окремого блоку. Якщо не проти, у джуна заповнимо описом щодо лідерських навичок, а сеньору розпишемо термін "Багатозадачність". Як дивишься на це?

Цілком на ваш розсуд. Список компетенцій був отриманий за допомогою опитувань (а це суб'єктивна річ), і аналізу І те як він складався, мається на увазі що навички у сеньора вимагає наявність відповідного на навички у мідла.

**Comment by den-vasyliev** [comment]
Пропоную Вам відразу PR зробити, для комʼюніті буде корисно!

**Comment by den-vasyliev** [comment]
Closed with [commit](https://github.com/den-vasyliev/SRE-Competency-Matrix/commit/2817a82cee3e2659b85f33fa13f9c04585164117)
